"""
api/session.py
--------------
In-memory conversation session store.

Tracks conversation history per session so the classifier can resolve
follow-up questions like "What about the other one?" or "Compare their
insider activity" by looking at what was previously discussed.

Each session stores:
  - session_id      : unique identifier generated by the frontend
  - history         : list of previous turns (question + tickers + summary)
  - last_tickers    : the tickers discussed in the most recent turn
  - last_query_type : SINGLE / COMPARE / FOLLOWUP / GENERAL

Note: In-memory storage — sessions are lost if the server restarts.
Acceptable for the hackathon demo scope.
"""

import uuid
from datetime import datetime
from typing import Optional

# ── In-memory store ───────────────────────────────────────────────────────────
_sessions: dict[str, dict] = {}

MAX_HISTORY_TURNS = 10


def create_session() -> str:
    """Create a new session and return its ID."""
    session_id = str(uuid.uuid4())
    _sessions[session_id] = {
        "session_id"      : session_id,
        "created_at"      : datetime.utcnow().isoformat(),
        "last_tickers"    : [],
        "last_query_type" : None,
        "history"         : [],
    }
    return session_id


def get_session(session_id: str) -> dict | None:
    """Return a session by ID, or None if it doesn't exist."""
    return _sessions.get(session_id)


def get_or_create_session(session_id: Optional[str]) -> tuple[str, dict]:
    """
    Return existing session or create a new one.
    Returns (session_id, session_dict).
    """
    if session_id and session_id in _sessions:
        return session_id, _sessions[session_id]
    new_id = create_session()
    return new_id, _sessions[new_id]


def add_turn(
    session_id    : str,
    question      : str,
    tickers       : list[str],
    query_type    : str,
    answer_summary: str,
) -> None:
    """
    Record a completed turn in the session history.

    Args:
        session_id     : The session to update
        question       : The user's question
        tickers        : Tickers that were resolved for this turn
        query_type     : SINGLE / COMPARE / FOLLOWUP / GENERAL
        answer_summary : One-sentence summary of the answer for context
    """
    session = _sessions.get(session_id)
    if not session:
        return

    turn = {
        "question"      : question,
        "tickers"       : tickers,
        "query_type"    : query_type,
        "answer_summary": answer_summary,
        "timestamp"     : datetime.utcnow().isoformat(),
    }

    session["history"].append(turn)
    session["last_tickers"]    = tickers
    session["last_query_type"] = query_type

    # Keep history bounded
    if len(session["history"]) > MAX_HISTORY_TURNS:
        session["history"] = session["history"][-MAX_HISTORY_TURNS:]


def get_history_as_text(session_id: str) -> str:
    """
    Format the session history as readable text for the classifier prompt.
    Resolves references like 'the second one' or 'both of them'.
    """
    session = _sessions.get(session_id)
    if not session or not session["history"]:
        return "No previous conversation history."

    lines = ["Previous conversation turns:"]
    for i, turn in enumerate(session["history"], 1):
        tickers_str = ", ".join(turn["tickers"]) if turn["tickers"] else "unknown"
        lines.append(
            f"  Turn {i}: [{turn['query_type']}] "
            f"Q: \"{turn['question']}\" | "
            f"Tickers: {tickers_str} | "
            f"Summary: {turn['answer_summary']}"
        )
    return "\n".join(lines)


def delete_session(session_id: str) -> bool:
    """Delete a session. Returns True if it existed."""
    if session_id in _sessions:
        del _sessions[session_id]
        return True
    return False