"""
memory/session_store.py
-----------------------
In-memory conversation history store for the Financial RAG Engine.

Each session is identified by a session_id (UUID generated by the frontend).
The store keeps the last MAX_TURNS question+answer pairs per session,
which get prepended to the synthesis prompt as conversation context.

Why in-memory (not Redis/Postgres):
  For a hackathon demo this is sufficient — no extra Docker services,
  no schema migrations, zero setup. The tradeoff is that history is lost
  on server restart, which is acceptable for a demo environment.

Data structure per session:
  {
    "session_id": {
      "turns": [
        {
          "role"    : "user",
          "content" : "Compare GME and NVIDIA",
          "tickers" : ["GME", "NVDA"],   ← list (was single ticker)
          "ticker"  : "GME",             ← backward-compat: first ticker
          "turn"    : 1,
        },
        {
          "role"    : "assistant",
          "content" : "GME carries higher risk than NVDA due to...",
          "tickers" : ["GME", "NVDA"],
          "ticker"  : "GME",
          "turn"    : 1,
        },
        ...
      ],
      "last_active": <timestamp>
    }
  }
"""

import time
from collections import defaultdict
from typing import Optional, List

# ── Constants ─────────────────────────────────────────────────────────────────
MAX_TURNS   = 10      # Keep last 10 Q+A pairs per session
SESSION_TTL = 3600    # Expire sessions after 1 hour of inactivity (seconds)

# ── Store ─────────────────────────────────────────────────────────────────────
_store: dict = defaultdict(lambda: {"turns": [], "last_active": time.time()})


# ── Internal helpers ──────────────────────────────────────────────────────────

def _evict_expired() -> None:
    """Remove sessions that have been inactive longer than SESSION_TTL."""
    now     = time.time()
    expired = [sid for sid, s in _store.items()
               if now - s["last_active"] > SESSION_TTL]
    for sid in expired:
        del _store[sid]
    if expired:
        print(f"[SessionStore] Evicted {len(expired)} expired session(s).")


# ── Public API ────────────────────────────────────────────────────────────────

def get_history(session_id: str) -> list[dict]:
    """
    Return the conversation history for a session as a list of turn dicts.
    Returns an empty list for unknown or expired sessions.
    """
    _evict_expired()
    session = _store.get(session_id)
    if not session:
        return []
    return session["turns"]


def append_turn(
    session_id    : str,
    question      : str,
    answer_summary: str,
    tickers       : List[str],
    # backward-compat: old callers may still pass ticker= as a kwarg
    ticker        : Optional[str] = None,
) -> None:
    """
    Append a completed Q+A exchange to the session history.

    Args:
        session_id     : Unique session identifier from the frontend
        question       : The user's original question
        answer_summary : A 2-3 sentence plain-text summary of the analysis
        tickers        : List of tickers discussed ([] for portfolio/general turns)
        ticker         : Deprecated — ignored if `tickers` is provided
    """
    _evict_expired()

    # Normalise: if called the old way with ticker= only, convert to list
    if not tickers and ticker:
        tickers = [ticker]

    session = _store[session_id]
    session["last_active"] = time.time()

    turn_number   = len(session["turns"]) // 2 + 1
    primary_ticker = tickers[0] if tickers else None

    session["turns"].append({
        "role"   : "user",
        "content": question,
        "tickers": tickers,
        "ticker" : primary_ticker,   # backward-compat
        "turn"   : turn_number,
    })
    session["turns"].append({
        "role"   : "assistant",
        "content": answer_summary,
        "tickers": tickers,
        "ticker" : primary_ticker,   # backward-compat
        "turn"   : turn_number,
    })

    # Keep only last MAX_TURNS exchanges (2 entries per turn)
    max_entries = MAX_TURNS * 2
    if len(session["turns"]) > max_entries:
        session["turns"] = session["turns"][-max_entries:]


def format_history_for_prompt(history: list[dict]) -> str:
    """
    Format conversation history into a clean string block
    for prepending to the synthesis prompt.

    Output format:
      [CONVERSATION HISTORY]
      Turn 1 | User [GME, NVDA]: Compare GME and NVIDIA
      Turn 1 | Assistant [GME, NVDA]: GME carries higher risk...
      Turn 2 | User [GME, NVDA]: Which one has more insider activity?
      Turn 2 | Assistant [GME, NVDA]: ...
      [END HISTORY]

    Returns an empty string if history is empty.
    """
    if not history:
        return ""

    lines = ["[CONVERSATION HISTORY — use this context to answer follow-up questions]"]
    for entry in history:
        role    = entry["role"].capitalize()
        tickers = entry.get("tickers") or []
        # fall back to old-style single ticker field for legacy sessions
        if not tickers and entry.get("ticker"):
            tickers = [entry["ticker"]]
        ticker_label = f" [{', '.join(tickers)}]" if tickers else ""
        turn    = entry.get("turn", "?")
        content = entry["content"]
        lines.append(f"  Turn {turn} | {role}{ticker_label}: {content}")
    lines.append("[END CONVERSATION HISTORY]\n")

    return "\n".join(lines)


def clear_session(session_id: str) -> None:
    """Explicitly clear a session's history (e.g. user clicks 'New Chat')."""
    if session_id in _store:
        del _store[session_id]


def session_count() -> int:
    """Return the number of active sessions (for monitoring)."""
    _evict_expired()
    return len(_store)