"""
memory/session_store.py
-----------------------
In-memory conversation history store for the Financial RAG Engine.

Each session is identified by a session_id (UUID generated by the frontend).
The store keeps the last MAX_TURNS question+answer pairs per session,
which get prepended to the synthesis prompt as conversation context.

Why in-memory (not Redis/Postgres):
  For a hackathon demo this is sufficient — no extra Docker services,
  no schema migrations, zero setup. The tradeoff is that history is lost
  on server restart, which is acceptable for a demo environment.

  Upgrading to Redis later is a one-file change: replace the dict with
  redis.get() / redis.set() calls using the same interface.

Data structure per session:
  {
    "session_id": [
      {
        "role"    : "user",
        "content" : "What is Boeing's situation?",
        "ticker"  : "BA",
        "turn"    : 1,
      },
      {
        "role"    : "assistant",
        "content" : "Boeing's 10-K warns of... [summary]",
        "ticker"  : "BA",
        "turn"    : 1,
      },
      ...
    ]
  }

The assistant turn stores a compact summary of the analysis
(not the full JSON response) to keep the context window manageable.
"""

import time
from collections import defaultdict
from typing import Optional

# ── Constants ─────────────────────────────────────────────────────────────────
MAX_TURNS      = 10    # Keep last 10 Q+A pairs per session
SESSION_TTL    = 3600  # Expire sessions after 1 hour of inactivity (seconds)

# ── Store ─────────────────────────────────────────────────────────────────────
# { session_id: {"turns": [...], "last_active": timestamp} }
_store: dict = defaultdict(lambda: {"turns": [], "last_active": time.time()})


# ── Public API ────────────────────────────────────────────────────────────────

def get_history(session_id: str) -> list[dict]:
    """
    Return the conversation history for a session as a list of turn dicts.
    Returns an empty list for unknown or expired sessions.
    """
    _evict_expired()
    session = _store.get(session_id)
    if not session:
        return []
    return session["turns"]


def append_turn(session_id: str, question: str, answer_summary: str, ticker: Optional[str]) -> None:
    """
    Append a completed Q+A exchange to the session history.

    Stores a compact summary of the answer rather than the full JSON
    response — this keeps the context window manageable while still
    giving the model enough context to answer follow-up questions.

    Args:
        session_id     : Unique session identifier from the frontend
        question       : The user's original question
        answer_summary : A 2-3 sentence plain-text summary of the analysis
        ticker         : The ticker discussed, if any (for context)
    """
    _evict_expired()

    session = _store[session_id]
    session["last_active"] = time.time()

    turn_number = len(session["turns"]) // 2 + 1

    session["turns"].append({
        "role"   : "user",
        "content": question,
        "ticker" : ticker,
        "turn"   : turn_number,
    })
    session["turns"].append({
        "role"   : "assistant",
        "content": answer_summary,
        "ticker" : ticker,
        "turn"   : turn_number,
    })

    # Keep only last MAX_TURNS exchanges (2 entries per turn)
    max_entries = MAX_TURNS * 2
    if len(session["turns"]) > max_entries:
        session["turns"] = session["turns"][-max_entries:]


def format_history_for_prompt(history: list[dict]) -> str:
    """
    Format conversation history into a clean string block
    for prepending to the synthesis prompt.

    Output format:
      [CONVERSATION HISTORY]
      Turn 1 | User (BA): What is Boeing's situation?
      Turn 1 | Assistant: Boeing's 10-K reveals serious quality control...
      Turn 2 | User (BA): Is that CEO purchase unusual?
      Turn 2 | Assistant: The CEO purchased 100K shares, which is...
      [END HISTORY]

    Returns an empty string if history is empty.
    """
    if not history:
        return ""

    lines = ["[CONVERSATION HISTORY — use this context to answer follow-up questions]"]
    for entry in history:
        role    = entry["role"].capitalize()
        ticker  = f" ({entry['ticker']})" if entry.get("ticker") else ""
        turn    = entry.get("turn", "?")
        content = entry["content"]
        lines.append(f"  Turn {turn} | {role}{ticker}: {content}")
    lines.append("[END CONVERSATION HISTORY]\n")

    return "\n".join(lines)


def clear_session(session_id: str) -> None:
    """Explicitly clear a session's history (e.g. user clicks 'New Chat')."""
    if session_id in _store:
        del _store[session_id]


def session_count() -> int:
    """Return the number of active sessions (for monitoring)."""
    _evict_expired()
    return len(_store)


# ── Internal helpers ──────────────────────────────────────────────────────────

def _evict_expired() -> None:
    """Remove sessions that have been inactive for more than SESSION_TTL seconds."""
    now     = time.time()
    expired = [
        sid for sid, data in _store.items()
        if now - data["last_active"] > SESSION_TTL
    ]
    for sid in expired:
        del _store[sid]